#if !canImport(ObjectiveC)
import XCTest

extension TestCHalf {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestCHalf = [
        ("testArithmeticFunctions", testArithmeticFunctions),
        ("testConstructorFunctions", testConstructorFunctions),
        ("testConvertingToFromRawValue", testConvertingToFromRawValue),
        ("testConvertToFromPrimitiveValues", testConvertToFromPrimitiveValues),
        ("testLogicFunctions", testLogicFunctions),
        ("testMiscellaneousFunctions", testMiscellaneousFunctions),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TestCHalf.__allTests__TestCHalf),
    ]
}
#endif // #if !canImport(ObjectiveC)
