name: Carthage
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '.github/**' # Ignore all files under '.github'
      - '!.github/workflows/carthage.yml' # Except for this workflow
      - '.gitignore'
      - '.remarkrc'
      - 'codecov.yml'
      - 'Documentation/**'
      - 'LICENSE'
      - 'Package.swift'
      - 'README.md'
      - 'Tests/**'
      - 'Half.podspec'

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-13]
        xcode: ['15.0']

    name: Build
    runs-on: ${{ matrix.os }}
    env:
      LOGSDIR: /tmp/.half.carthage/Logs

    steps:
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        mkdir -p "$LOGSDIR"
        touch "$LOGSDIR/Build.log"

    - name: Install Carthage
      run: |
        brew update
        brew install carthage

    - name: Create Cartfile
      run: |
        # Delete all of the old tags (if any) and create a new tag for building
        git tag | xargs git tag -d
        git tag 1.0
        
        echo "git \"file://$(pwd)\"" > ./Cartfile

    - name: Build
      run: |
        ./scripts/carthage.sh update --log-path "$LOGSDIR/Build.log"

    - name: Upload Logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: BuildLog
        path: ${{ env.LOGSDIR }}/*.log
