name: Cocoapods
on: [push, workflow_dispatch]

jobs:
  lint:
    strategy:
      matrix:
        linttype: [Dynamic, Static]

    name: Lint
    runs-on: macOS-11
    env:
      LINT_TYPE: ${{ matrix.linttype }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: latest

    - name: Lint
      run: |
        if [ "$LINT_TYPE" == "Dynamic" ]; then
            pod lib lint
        else
            pod lib lint --use-libraries
        fi
