name: Documentation
defaults:
  run:
    shell: bash -eo pipefail {0}
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/documentation.yml'
      - '**.swift' # DocC only considers Swift files
      - 'Documentation/Half.docc/**'

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-13]
        xcode: ['15.0']

    name: Build Documentation
    runs-on: ${{ matrix.os }}
    env:
      LOGSDIR: /tmp/.half.documentation/Logs

    steps:
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Environment
      run: |
        mkdir -p "$LOGSDIR"

    - name: Build Documentation
      run: |
        xcodebuild docbuild -project "Half.xcodeproj" -scheme "Half" -destination "generic/platform=iOS Simulator" SKIP_SWIFTLINT=YES ARCHS="x86_64" 2>&1 | tee "$LOGSDIR/build.log"

    - name: Upload Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Logs
        path: ${{ env.LOGSDIR }}/*.log
