name: SwiftLint
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**.swift'

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-13]
        xcode: ['15.0']

    name: Run SwiftLint
    runs-on: ${{ matrix.os }}

    steps:
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run SwiftLint
      run: |
        swiftlint lint --reporter github-actions-logging
