name: XCFramework
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '.github/**' # Ignore all files under '.github'
      - '!.github/workflows/xcframework.yml' # Except for this workflow
      - '.gitignore'
      - '.remarkrc'
      - '.swiftlint.yml'
      - 'codecov.yml'
      - 'Documentation/**'
      - 'LICENSE'
      - 'Package.swift'
      - 'README.md'
      - 'Tests/**'
      - 'Half.podspec'

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-13]
        xcode: ['15.0']

    name: Build
    runs-on: ${{ matrix.os }}
    env:
      TMPDIR: /tmp/.half.xcframework.build

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        mkdir -p "${TMPDIR}/Output"
        mkdir -p "${TMPDIR}/Logs"

    - name: Build
      run: |
        ./scripts/xcframework.sh --build-dir "${TMPDIR}" -- RUN_DOCUMENTATION_COMPILER=NO SKIP_SWIFTLINT=YES

    - name: Upload Logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: BuildLogs
        path: ${{ env.TMPDIR }}/Logs/*.log
